### ISSUE TITLE
Cross-reference issues in documentation

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/prioritizr#340]
CRAN checks are producing the following NOTEs (https://cran.r-project.org/web/checks/check_results_prioritizr.html):

```
Found the following Rd file(s) with Rd \link{} targets missing package
  anchors:
    OptimizationProblem-methods.Rd: dgCMatrix-class
    adjacency_matrix.Rd: dsCMatrix-class
    boundary_matrix.Rd: dsCMatrix-class
    branch_matrix.Rd: dgCMatrix-class
    connectivity_matrix.Rd: dsCMatrix-class
    marxan_boundary_data_to_matrix.Rd: dgCMatrix-class
    marxan_connectivity_data_to_matrix.Rd: dgCMatrix-class
    problem.Rd: dgCMatrix-class
    proximity_matrix.Rd: dsCMatrix-class
    rescale_matrix.Rd: Matrix-class
    rij_matrix.Rd: dgCMatrix-class
  Please provide package anchors for all Rd \link{} targets not in the
  package itself and the base packages.
Flavors: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/prioritizr-00check.html), [r-devel-windows-x86_64](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/prioritizr-00check.html)
```
